{{- define "amconfig.routes" -}}
{{- range . }}
- receiver: {{ .receiver | quote }}
  {{- if .matchers }}
  matchers:
    {{- range .matchers }}
    - name: {{ .key | quote }}
      matchType: {{ .op | quote }}
      value: {{ .value | quote }}
    {{- end }}
  {{- end }}
  {{- if .routes }}
  routes:
{{ include "amconfig.routes" .routes | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ if .Values.global.product }}{{ .Values.global.product }}-{{ end }}{{ .Values.configName }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  route:
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: {{ if .Values.global.product }}"{{ .Values.global.product }}-{{ .Values.defaultReceiver }}"{{ else }}{{ .Values.defaultReceiver | quote }}{{ end }}
    {{- if .Values.routeMatchers }}
    matchers:
      {{- range .Values.routeMatchers }}
      - name: {{ .key | quote }}
        matchType: {{ .op | quote }}
        value: {{ .value | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.routeRules }}
    routes:
{{ include "amconfig.routes" .Values.routeRules | indent 4 }}
    {{- end }}

  {{- if .Values.inhibitRules }}
  inhibitRules:
    {{- range .Values.inhibitRules }}
    - sourceMatch:
        {{- range .sourceMatchers }}
        - name: {{ .key | quote }}
          matchType: {{ .op | quote }}
          value: {{ .value | quote }}
        {{- end }}
      targetMatch:
        {{- range .targetMatchers }}
        - name: {{ .key | quote }}
          matchType: {{ .op | quote }}
          value: {{ .value | quote }}
        {{- end }}
      {{- if .equal }}
      equal:
        {{- range .equal }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

  receivers:
    {{- if .Values.receivers }}
    {{- range .Values.receivers }}
    - name: {{ if $.Values.global.product }}"{{ $.Values.global.product }}-{{ .name }}"{{ else }}{{ .name | quote }}{{ end }}
      {{- if .webhook_configs }}
      webhookConfigs:
        {{- range .webhook_configs }}
        - url: {{ .url | quote }}
          sendResolved: {{ .send_resolved }}
        {{- end }}
      {{- end }}
      {{- if .slack_configs }}
      slackConfigs:
        {{- range .slack_configs }}
        - apiURL: {{ .api_url | quote }}
          channel: {{ .channel | quote }}
          sendResolved: {{ .send_resolved }}
        {{- end }}
      {{- end }}
      {{- if .pagerduty_configs }}
      pagerdutyConfigs:
        {{- range .pagerduty_configs }}
        - routingKey: {{ .routing_key | quote }}
          sendResolved: {{ .send_resolved }}
        {{- end }}
      {{- end }}
      {{- if .email_configs }}
      emailConfigs:
        {{- range .email_configs }}
        - to: {{ .to | quote }}
          from: {{ .from | quote }}
          smarthost: {{ .smarthost | quote }}
          requireTLS: false
        {{- end }}
      {{- end }}
    {{- end }}
    {{- else }}
    - name: {{ if .Values.global.product }}"{{ .Values.global.product }}-{{ .Values.defaultReceiver }}"{{ else }}{{ .Values.defaultReceiver | quote }}{{ end }}
    {{- range .Values.routeRules }}
    {{- if ne .receiver $.Values.defaultReceiver }}
    - name: {{ if $.Values.global.product }}"{{ $.Values.global.product }}-{{ .receiver }}"{{ else }}{{ .receiver | quote }}{{ end }}
    {{- end }}
    {{- end }}
    {{- end }}
