apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ if .Values.global.product }}{{ .Values.global.product }}-{{ end }}{{ .Values.alertSuite.name }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
    - name: {{ if .Values.global.product }}{{ .Values.global.product }}-{{ end }}{{ .Values.alertSuite.name }}
      rules:
        {{- range .Values.alertSuite.rules }}
        - alert: {{ .ruleName }}
          expr: {{ .expr | quote }}
          {{- if .for }}
          for: {{ .for }}
          {{- end }}
          labels:
            severity: {{ .severity }}
            {{- with .labels }}
            {{- range $k, $v := . }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
            {{- end }}
          annotations:
            {{- if .description }}
            description: {{ .description | quote }}
            {{- end }}
            summary: {{ .ruleName | quote }}
        {{- end }}
