name: high-threshold
expr: '{{ .metric }} {{ .op }} {{ .threshold }}'
vars:
  - name: metric
    type: metric
    description: metric name or PromQL expression
  - name: op
    type: string
    description: comparison operator (> < >= <=)
  - name: threshold
    type: number
    description: alert threshold value
