apiVersion: v2
name: platform-routing
version: 1.0.0
type: application
dependencies:
  - name: platform-infra
    version: 1.0.0
    repository: file://../../../alert-suite/platform-infra/v1.0.0
  - name: api-service
    version: 1.0.0
    repository: file://../../../alert-suite/api-service/v1.0.0
